2nd edit

diff --git a/SW/create_db b/SW/create_db
--- a/SW/create_db
+++ b/SW/create_db
@@ -5,53 +5,73 @@ cd ../DATA_BASE_CREATED
 
 while true
 do 
-echo "please enter your database name" 
-read name_db 
-# matnse4 case can't start with speical character!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+#echo "please enter your database name"
+#read name_db 
+#hena  type --entry 3l4an ya5od input mn el user w y3melo store f name_db
+
+name_db=$(zenity --entry --title="Create Database" --text="please enter your database name ")
+
+
+# $?: This is a special variable in bash that always 
+# contains the exit status of the most recently executed command. 
+
+
+
+# kda check exit
+if [ $? -eq 1 ]
+then
+   exit 0
+fi
+
+# matnse4 case can't start with speical character!!!(Done)
 case $name_db in
  # is empty
  "" )
-  echo "database name can't be empty"
+   # henna --error de to display eror msg
+   zenity --error --text="database name can't be empty"
+    echo "database name can't be empty"
    continue
    ;;
 
     #condition da m4 48al kways 8er f el nos bs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
   *[[:space:]] | *[[:space:]]* | [[:space:]]*   )
-   echo "database name can't contain space"
+     zenity --error --text="database name can't contain space"
+     #echo "database name can't contain space"
     continue
    ;;
   [0-9]* )
-  echo "database name can't start with number"
+
+  zenity --error --text="database name can't start with number"
+  #echo "database name can't start with number"
   continue
    ;;
-
-
-  # 8lat ya shoshoo [;-#-!-@-%-^-&-*-(-)-=-_-+-~]*[a-zA-Z_0-9])
-  *[;\#\-\!\-\@\-\%\-\^\-\&\-\*\-\(\)\-\-\=\-\_\+\-\~]*)
-  echo "database name can't start with speacial characters "
-  continue
-   ;;
+ [!a-zA-Z0-9_]*)
+       zenity --error --text="database name can't contain special characters."
+         echo "database name can't contain special characters."
+         continue
+         ;;    
 
    # 3ayza a5leha 2 cases speaical char w elba2y 
   *[a-zA-Z]*[a-zA-Z_0-9] | [a-zA-Z_]) 
       if  [ -e $name_db ]
       then 
-         echo "the database is already exist"
+         zenity --error --text="the database is already exist"
+        # echo "the database is already exist"
          continue 
       else
     # momken 22ol do you want to  edit the exisiting db 
           mkdir $name_db 
+          #de b display information msg box
+          zenity --info --text="the database created sussecfully"
+
           break 
       fi
       ;;
    *)
-    echo "database name is invalid"
+    zenity --error --text="database name is invalid"
+    # echo "database name is invalid"
      continue 
      ;; 
 esac
 done
-# read -p "please enter your database name" $name_db 
-
-# ( find  $name_db `ls -F | grep /` &> ~/../../dev/null ) #list files then search
-
 cd - 2> /dev/null
diff --git a/SW/create_table b/SW/create_table
--- a/SW/create_table
+++ b/SW/create_table
@@ -1,8 +1,6 @@
 #!/usr/bin/bash
 
 
-
-
  
 # list existing tables 
 
@@ -11,40 +9,65 @@ echo "........existing tables........"
 ls -s
 
 #handel paRT LMa by5las yrga3 feen !!!!!!!!!!!!!!!!!
-# matnse4 case can't start with speical character!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
 # create table 
 while true 
 do
-   read -p "enter name of table you want to create:"  table_name
+     
+
+   table_name=$(zenity --entry --title="Table Name" --text="enter name of table you want to create:")
+
+
+    if [ $? -eq 1 ]
+    then
+        exit 0
+    fi
+
+   #read -p "enter name of table you want to create:"  table_name
 
   case $table_name in
   "" )
+   # lma zawedt gui mabt4t8l4  
+   #################################################################################################################################################
+   zenity --error --text="table name can't be empty"
    echo "table name can't be empty"
    continue
    ;;
    #condition da m4 48al kways 8er f el nos bs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
   *[[:space:]] | *[[:space:]]* | [[:space:]]*   )
+
+    zenity --error --text="table name can't contain space"
     echo "table name can't contain space"
     continue
    ;;
   [0-9]* )
+
+    zenity --error --text="table name can't start with number"
     echo "table name can't start with number"
     continue
    ;;
+ [!a-zA-Z0-9_]*)
+    zenity --error --text="table name can't contain special characters."
+    echo "table name can't contain special characters."
+    continue
+    ;;  
    # 3ayza a5leha 2 cases speaical char w elba2y 
  *[a-zA-Z]*[a-zA-Z_0-9] | [a-zA-Z_])
     if [ -e $table_name ] 
 	then
+      zenity --error --text="table already exist"
 	  echo  table already exist
 	  continue    
 	else
 	
       touch $table_name
-	fi 
-	  echo the table created successfully 
+      zenity --info --text="the table created successfully "
+      echo the table created successfully 
       break
+	fi 
+	 
 	;;
    * )
+   zenity --error --text="invaled table name"
    echo invaled table name
    continue
    ;;
@@ -57,36 +80,61 @@ done
 
 while true 
 do 
-  read -p "please enter columns number to be created: " numCol
+  #####33333
+  numCol=$(zenity --entry --title="Number Columns" --text="please enter Number of Columns to be created:")
+
+  #read -p "please enter Number of Columns to be created: " numCol
 
   case $numCol in 
   *[0])
+
+    zenity --error --text="number of columns cannot be zero"
     echo number of columns cannot be zero 
 	continue
 	;;
   *[1-9] | *[1-9]*[0-9] )
+
+     zenity --info --text="your table will have $numCol columns"
      echo your table will have $numCol columns 
+
+
+
 	   for ((i=1;i<=$numCol;i++))
 	   do
 		    line=""
-		    read -p "please enter $i column name: (note your first column will be primary key)" colName
+		    
            while true 
            do 
+
+
+           ##########
+           colName=$(zenity --entry --title="Columns Name" --text="please enter $i column name: (note your first column will be primary key):")
+           # read -p "please enter $i column name: (note your first column will be primary key)" colName
+
+
+
            case $colName in
            "")
+              zenity --error --text="column name can't be empty"
               echo "column name can't be empty"
               continue
               ;; 
               #condition da m4 48al kways 8er f el nos bs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
            *[[:space:]] | *[[:space:]]* | [[:space:]]*   )
+                zenity --error --text="column name can't contain space"
                 echo "column name can't contain space"
                 continue
                  ;;  
            [0-9]* )
+               zenity --error --text="column name can't start with number"
                echo "column name can't start with number"
                 continue
                 ;;  
-                 
+            [!a-zA-Z0-9_]*)
+                zenity --error --text="table name can't contain special characters."
+                echo "table name can't contain special characters."
+                continue
+                ;;    
           	  	# 3ayza a5leha 2 cases speaical char w elba2y 
             *[a-zA-Z]*[a-zA-Z_0-9] | [a-zA-Z_]) 
                   if [ $i -eq 1 ]
@@ -95,9 +143,14 @@ do
                              line+=$colName:
                              while true 
                                   do
-                                  read -p "please enter $i column Datatype (int/str): " colType
+
+                                  #######
+                                   colType=$(zenity --entry --title="Columns Type" --text="please enter $i column Datatype (int/str): ")
+           
+                                  #read -p "please enter $i column Datatype (int/str): " colType
                                   case $colType in
                                    "")
+                                     zenity --error --text="Datatype for column $i can't be empty"
                                      echo "Datatype for column $i can't be empty"
                                      continue
                                      ;;
@@ -106,6 +159,7 @@ do
                                         break
                                         ;;
                                     *)
+                                        zenity --error --text="invailid data type for column"
                                         echo invailid data type for column
                                         continue
                                         ;;
@@ -114,8 +168,9 @@ do
 
                   else 
                            ##########################Mahtag ytzabat m4 48aaalllaaaa################################### 
-                          if ( find $colName `head -1 $table_name` 2> /dev/null ) 
+                          if  (grep -q "^$colName:" .$table_name"_metadata" ) 
                  	        then  
+                                  zenity --error --text="culomn name $colName is already exist "
                                   echo culomn name $colName is already exist 
                                   continue
                           else        
@@ -123,9 +178,14 @@ do
                                  
                                   while true 
                                   do
-                                  read -p "please enter $i column Datatype (int/str): " colType
+
+
+                                  #######
+                                  colType=$(zenity --entry --title="Columns Type" --text="please enter $i column Datatype (int/str): ")
+                                  #read -p "please enter $i column Datatype (int/str): " colType
                                   case $colType in
                                    "")
+                                     zenity --error --text="Datatype for column $i can't be empty"
                                      echo "Datatype for column $i can't be empty"
                                      continue
                                      ;;
@@ -134,6 +194,7 @@ do
                                         break
                                         ;;
                                     *)
+                                        zenity --error --text="invailid data type for column"
                                         echo invailid data type for column
                                         continue
                                         ;;
@@ -144,6 +205,7 @@ do
                   fi
                  # .for hidden file
                  echo $line >> .$table_name"_metadata" 
+                 zenity --info --text="meta data file created sucsfully "
                  echo meta data file created sucsfully 
 
 
@@ -153,6 +215,8 @@ do
                 break;;
                
             * )
+
+                 zenity --error --text="column name is invalid"
                  echo "column name is invalid"
                  continue
                  ;;
@@ -165,14 +229,11 @@ do
       break
       ;;
   * )
+
+     zenity --error --text="invalid input for column name"
      echo invalid input for column name
 	continue
 	;;
   esac
   
-done
-
-
-
-
-  
+done 
diff --git a/SW/insert_table b/SW/insert_table
--- a/SW/insert_table
+++ b/SW/insert_table
@@ -5,44 +5,30 @@ echo "choose table you want to insert in "
 
 array=( `ls` )
 
-select choice in ${array[*]}
-do 
-   if [ $REPLY -gt ${#array[*]} ]
-  then 
-    echo $REPLY not in menue
-    continue
-   else
-     table_name=${array[${REPLY}-1]} 2> /dev/null # array start from 0 f lazem 3l4an my3ml4 delete lly ba3do 
-     echo 'you arre now inside '${array[${REPLY}-1]}' table' 
+choice=$(zenity --list --title="Choose Table to Insert" --text="Select a table to insert:" --column="Tables" "${array[@]}")
 
-     break 
-   fi
-done
-
-############checking if meta data file exists#########################
-# metadata_file=$(find . -name ".$table_name"_metadata""  2>/dev/null)
-# if [[ -z $metadata_file ]]; then
-#     echo "Metadata file not found!"
-#     exit 1
-# else
-#     echo "Metadata file found: $metadata_file"
-# fi
-
-# if ( find . -name ".$table_name"_metadata"" &>= ../../dev/null )
-# then
-#     metadata_file=.$table_name"_metadata"   
-#     echo metadata file found
-# else 
-#      echo the metadata file not found
-# fi     
+if [ $? -eq 1 ]; then
+  exit 0
+fi
 
 
+table_name=$choice
+zenity --info --text="You are now inside $table_name table"
 
-# if [[ ! -f .$table_name"_metadata" || ! -s .$table_name"_metadata" ]];
-# then
-#     echo "Metadata file for $table_name is missing or empty."
-#     exit 1
-# fi
+# da ll input lma ykon numbers 
+# select choice in ${array[*]}
+# do 
+#    if [ $REPLY -gt ${#array[*]} ]
+#   then 
+#     echo $REPLY not in menue
+#     continue
+#    else
+#      table_name=${array[${REPLY}-1]} 2> /dev/null # array start from 0 f lazem 3l4an my3ml4 delete lly ba3do 
+#      echo 'you arre now inside '${array[${REPLY}-1]}' table' 
+
+#      break 
+#    fi
+# done
 
 
 
@@ -63,17 +49,6 @@ if [[ ${#names[@]} -eq 0 ]]; then
     exit 1
 fi
 
-# no need 5las grep 7altha #
-# PK_array=()
-# if [[ -f $table_name ]]
-# then
-#     PK_array=$(awk -F: '{print $1}' $table_name )
-# fi
-# echo pk  `echo $PK_array`
-
-
-
-
 
 
 
@@ -86,12 +61,16 @@ do
     do
         while true
         do
-            read -p "Enter value for ${names[i]} that has type (${types[i]}): " value
-            
+
+            value=$(zenity --entry --title="Insert Value" --text="enter value for ${names[i]} that has type (${types[i]}):")
+
+#            read -p "Enter value for ${names[i]} that has type (${types[i]}): " value
+             
             
             if [[ -z $value ]]
             then
-                echo "Value can't be empty."
+                zenity --error --text="Value can't be empty"
+                echo "Value can't be empty"
                 continue
             fi
             
@@ -106,7 +85,8 @@ do
                         
                         if grep -q "^$value:" "$table_name"
                          then
-                             echo "primary key $value already exists in table $table_name."
+                             zenity --error --text="primary key $value already exists in table $table_name"
+                             echo "primary key $value already exists in table $table_name"
                              continue
                         else
                              row+="$value:"
@@ -117,7 +97,8 @@ do
                         break
                     fi
                 else
-                    echo "value must be an integer."
+                    zenity --error --text="value must be an integer"
+                    echo "value must be an integer"
                     continue
                 fi
             fi
@@ -132,7 +113,8 @@ do
                    #3l4an 2t2ked en el input ely hyd5alo m4 mtkrar
                     if grep -q "^$value:" "$table_name"
                     then
-                        echo "Primary key $value already exists in table $table_name."
+                        zenity --error --text="primary key $value already exists in table $table_name"
+                        echo "primary key $value already exists in table $table_name"
                         continue
                     else
                         row+="$value:"
@@ -144,29 +126,46 @@ do
                 fi
                
             fi
-
-            echo "Invalid value type for ${names[i]}."
+             zenity --error --text="invalid value type for ${names[i]}"
+            echo "invalid value type for ${names[i]}"
         done
     done
    
     row=${row%:}
-    echo "$row" >> $table_name 2>/dev/null     
-    echo "Row inserted successfully into $table_name."
+    echo "$row" >> $table_name 2>/dev/null   
+    zenity --info --text="row inserted successfully into $table_name"
+    echo "row inserted successfully into $table_name"
+    
+    row=${row%:}
+    echo "$row" >> $table_name 2>/dev/null   
+    zenity --info --text="row inserted successfully into $table_name"
+    echo "row inserted successfully into $table_name"
     
    
 
    PK_array+=" $row"
    PK_array=${PK_array%% *}
 
+   
+
+   PK_array+=" $row"
+   PK_array=${PK_array%% *}
+
    ########################--------------------######################
-    read -p "Do you want to insert another row? (yes/no): " check
-         if [[ "no" == $check ]]
-         then
-        	break
-          fi
+   
+    # 
+    # read -p "Do you want to insert another row? (yes/no): " check
+    #      if [[ "no" == $check ]]
+    #      then
+    #     	break
+    #       fi
+
+
+
+    if zenity --question --text="Do you want to insert another row?"
+    then
+       continue
+    else
+       break
+    fi
 done
-
-
-
-
-
